[package]
name = "salsa"
version = "0.14.1" # CHECK salsa-macros version
authors = ["Salsa developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/salsa-rs/salsa"
description = "A generic framework for on-demand, incrementalized computation (experimental)"
readme = "README.md"

[dependencies]
crossbeam = "0.7.1"
indexmap = "1.0.1"
linked-hash-map = "0.5.2"
log = "0.4.5"
parking_lot = "0.10.0"
rustc-hash = "1.0"
smallvec = "1.0.0"
rand = { version = "0.7", features = [ "small_rng" ] }

salsa-macros = { version = "0.14.1", path = "components/salsa-macros" }

[dev-dependencies]
rand_distr = "0.2.1"
diff = "0.1.0"
env_logger = "0.5.13"

[workspace]
