[package]
name = "salsa"
version = "0.17.0-pre.2" # CHECK salsa-macros version
authors = ["Salsa developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/salsa-rs/salsa"
description = "A generic framework for on-demand, incrementalized computation (experimental)"

[dependencies]
arc-swap = "1.4.0"
crossbeam-utils = { version = "0.8", default-features = false }
dashmap = "4.0.2"
hashlink = "0.7.0"
indexmap = "1.0.1"
lock_api = "0.4"
log = "0.4.5"
parking_lot = "0.11.0"
rustc-hash = "1.0"
smallvec = "1.0.0"
oorandom = "11"

salsa-macros = { version = "0.17.0-pre.2", path = "components/salsa-macros" }

[dev-dependencies]
diff = "0.1.0"
env_logger = "0.7"
linked-hash-map = "0.5.2"
rand = "0.7"
rand_distr = "0.2.1"
test-env-log = "0.2.7"
insta = "1.8.0"

[workspace]
members = [
    "components/salsa-macros",
    "components/salsa-entity-mock",
    "components/salsa-consumer-mock",
    "components/salsa-entity-macros",
]