[package]
name = "salsa"
version = "0.18.0"
authors = ["Salsa developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/salsa-rs/salsa"
description = "A generic framework for on-demand, incrementalized computation (experimental)"

[dependencies]
arc-swap = "1.6.0"
crossbeam = "0.8.1"
dashmap = "5.3.4"
hashlink = "0.8.0"
indexmap = "2"
log = "0.4.5"
orx-concurrent-vec = "1.8.0"
parking_lot = "0.12.1"
rustc-hash = "1.1.0"
salsa-macros = { path = "components/salsa-macros" }
smallvec = "1.0.0"

[dev-dependencies]
derive-new = "0.5.9"
expect-test = "1.4.0"
eyre = "0.6.8"
notify-debouncer-mini = "0.2.1"
ordered-float = "3.0"
rustversion = "1.0"
test-log = "0.2.11"
trybuild = "1.0"

[workspace]
members = ["components/salsa-macros"]
